providers:
  - nixpacks

build:
  nixpacksPlan:
    providers:
      - node
    phases:
      setup:
        nixPkgs:
          - nodejs
          - npm
      install:
        cmds:
          - npm ci
      build:
        cmds:
          - echo "No build step needed"
      start:
        cmd: npm start
